FROM 389941814333.dkr.ecr.eu-west-1.amazonaws.com/build/suricata-build:centos8
RUN yum install -y \
                chrpath \
                ocaml \
                ocaml-findlib \
                ocaml-findlib-devel \
                ocaml-ocamldoc
RUN git clone --depth 1 https://github.com/coccinelle/coccinelle.git
WORKDIR /coccinelle
RUN ./autogen && ./configure 
RUN make && make install
ENV PATH="/usr/local/bin:${PATH}"
WORKDIR /


