FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y \
		autoconf \
		automake \
		build-essential \
		curl \
		git \
		jq \
		libcap-ng-dev \
		libcap-ng0 \
		libevent-dev \
		libevent-pthreads-2.1.6 \
		libhiredis-dev \
		libjansson-dev \
		libjansson-dev \
		libmagic-dev \
		libnet1-dev \
		libnetfilter-queue-dev \
		libnetfilter-queue1 \
		libnfnetlink-dev \
		libnfnetlink0 \
		libpcap-dev \
		libpcre3 \
		libpcre3-dev \
		libpython2.7 \
		libtool \
		libyaml-0-2 \
		libyaml-dev \
		make \
		parallel \
		python3-yaml \
		software-properties-common \
		zlib1g \
		zlib1g-dev
RUN add-apt-repository -y ppa:npalix/coccinelle && \
    apt-get install -y coccinelle
RUN curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal --default-toolchain stable --component clippy --component rustfmt -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install --force cbindgen
