FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y \
                libpcre3 \
                libpcre3-dev \
                build-essential \
                autoconf \
                automake \
                curl \
                git \
                jq \
                libtool \
                libpcap-dev \
                libnet1-dev \
                libyaml-0-2 \
                libyaml-dev \
                libcap-ng-dev \
                libcap-ng0 \
                libmagic-dev \
                libnetfilter-queue-dev \
                libnetfilter-queue1 \
                libnfnetlink-dev \
                libnfnetlink0 \
                libhiredis-dev \
                libjansson-dev \
                libevent-dev \
                libevent-pthreads-2.1.6 \
                libjansson-dev \
                libpython2.7 \
                make \
                parallel \
                python3-yaml \
                rustc \
                software-properties-common \
                zlib1g \
                zlib1g-dev
RUN add-apt-repository -y ppa:npalix/coccinelle && \
      apt-get install -y coccinelle
RUN cargo install --force cbindgen
ENV PATH="/root/.cargo/bin:${PATH}"

