version: 0.2

env:
  variables:
    ARGS: "--enable-rust-strict"
    CFLAGS: "-Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused-function"
    EXTRA_CFLAGS: ""
  parameter-store:
  secrets-manager:

phases:
  pre_build:
    commands:
      - git clone https://github.com/OISF/libhtp -b 0.5.x
      - |
          cd suricata-update
          curl -L \
              https://github.com/OISF/suricata-update/archive/master.tar.gz | \
              tar zxvf - --strip-components=1
      - cd ..
      - |
        ./autogen.sh
        ./configure --enable-debug \
              --enable-lua \
              --enable-geoip \
              --enable-profiling \
              --enable-profiling-locks \
              ${ARGS}
  build:
    commands:
      - export CFLAGS="${CFLAGS} ${EXTRA_CFLAGS}"
      - make -j8
      - make -j8 check
